"""Command line entry point: python -m nhlmodel <command> ...

  synth     generate a synthetic league (pipeline testing only)
  build     NHL API + MoneyPuck raw files -> canonical tables
  backtest  walk-forward backtest + validation report
  tune      grid search (k, m, half-life, ...) + edge thresholds, report on a holdout window
  slate     price a day's games and props
"""
from __future__ import annotations

import argparse
import os
import time

import pandas as pd

from .config import DEFAULT, ModelConfig
from .data.schema import load_dir, save_dir


def _cfg(path):
    if path:
        from .tuning import load_config
        return load_config(path)
    return DEFAULT


def _data_notes(tables: dict, synthetic: bool) -> list[str]:
    notes = []
    if synthetic:
        notes.append("SYNTHETIC DATA: results only show the pipeline runs; they say nothing about real edges.")
    if "odds" not in tables:
        notes.append("No odds table: closing-line baselines, CLV and edge-threshold tuning are unavailable; "
                     "game-market baseline falls back to historical frequency.")
    notes.append("Historical lines/PP units are TOI-rank proxies unless real Daily Faceoff history is supplied.")
    notes.append("Walk-forward treats the lineup that actually dressed (and the actual starting goalie) as the "
                 "confirmed pre-game lineup.")
    return notes


def run_validation(bt: dict, tables: dict, cfg: ModelConfig, out: str, title: str, notes: list[str],
                   thresholds: dict | None = None, date_from=None):
    from .report import validation_markdown, write
    from .validation import attach_baselines, bet_summary, flagged_bets, market_report
    gm, pm = attach_baselines(bt, tables, cfg)
    if date_from is not None:
        gm, pm = gm[gm.date >= pd.Timestamp(date_from)], pm[pm.date >= pd.Timestamp(date_from)]
    preds = pd.concat([gm, pm], ignore_index=True)
    summary, calib = market_report(preds, cfg)
    bets = pd.DataFrame()
    if "odds" in tables:
        bets = flagged_bets(preds, tables["odds"], cfg, thresholds)
    bs = bet_summary(bets) if len(bets) else pd.DataFrame()
    cons = bt["consistency"]
    if date_from is not None and len(cons):
        cons = cons[cons.date >= pd.Timestamp(date_from)]
    md = validation_markdown(summary, calib, bs, bt["fit_log"], cons, cfg, title, notes)
    os.makedirs(out, exist_ok=True)
    write(os.path.join(out, "validation.md"), md)
    summary.to_csv(os.path.join(out, "market_summary.csv"), index=False)
    if len(bets):
        bets[bets.flag].to_csv(os.path.join(out, "flagged_bets.csv"), index=False)
    return summary, bets


def cmd_synth(a):
    from .data.synthetic import generate
    t = time.time()
    tables, _ = generate(seed=a.seed, seasons=tuple(a.seasons))
    save_dir(tables, a.out)
    open(os.path.join(a.out, "SYNTHETIC"), "w").write("generated by nhlmodel.data.synthetic\n")
    print(f"wrote {a.out} in {time.time()-t:.0f}s: " + ", ".join(f"{k}={len(v)}" for k, v in tables.items()))


def cmd_build(a):
    from .data import moneypuck, nhl_api
    nhl = nhl_api.fetch_games(a.start, a.end, cache_dir=os.path.join(a.raw, "nhl_api"))
    tables = moneypuck.build(a.raw, nhl)
    save_dir(tables, a.out)
    print("wrote", a.out, {k: len(v) for k, v in tables.items()})


def cmd_backtest(a):
    from .backtest import walk_forward
    tables = load_dir(a.data)
    cfg = _cfg(a.config)
    t = time.time()
    bt = walk_forward(tables, cfg, a.start, a.end, date_stride=a.stride, verbose=True)
    os.makedirs(a.out, exist_ok=True)
    for k, v in bt.items():
        v.to_csv(os.path.join(a.out, f"bt_{k}.csv"), index=False)
    synthetic = os.path.exists(os.path.join(a.data, "SYNTHETIC"))
    summary, _ = run_validation(bt, tables, cfg, a.out, f"Walk-forward backtest {a.start} to {a.end}",
                                _data_notes(tables, synthetic))
    print(summary[["market", "line", "n", "logloss", "logloss_base", "ece", "status"]].to_string(index=False))
    print(f"done in {time.time()-t:.0f}s -> {a.out}/validation.md")


def cmd_tune(a):
    from .backtest import walk_forward
    from .tuning import GRID, coordinate_search, save_config
    from .validation import attach_baselines, flagged_bets, tune_edge_thresholds
    tables = load_dir(a.data)
    cfg = _cfg(a.config)
    grid = GRID
    if a.params:
        grid = {k: v for k, v in GRID.items() if k in a.params.split(",")}
    print(f"coordinate search on {a.tune_start}..{a.tune_end} over {list(grid)}")
    best, log = coordinate_search(tables, cfg, a.tune_start, a.tune_end, grid=grid, passes=a.passes,
                                  date_stride=a.stride)
    os.makedirs(a.out, exist_ok=True)
    log.to_csv(os.path.join(a.out, "grid_search.csv"), index=False)
    print("final walk-forward over tune + holdout with tuned constants")
    bt = walk_forward(tables, best, a.tune_start, a.holdout_end, verbose=True)
    thresholds, tlog = dict(best.edge_threshold), pd.DataFrame()
    if "odds" in tables:
        gm, pm = attach_baselines(bt, tables, best)
        tune_preds = pd.concat([gm[gm.date <= pd.Timestamp(a.tune_end)], pm[pm.date <= pd.Timestamp(a.tune_end)]])
        bets = flagged_bets(tune_preds, tables["odds"], best)
        found, tlog = tune_edge_thresholds(bets)
        thresholds.update(found)
        tlog.to_csv(os.path.join(a.out, "edge_threshold_search.csv"), index=False)
    best = best.with_(edge_threshold=thresholds)
    save_config(best, os.path.join(a.out, "tuned_config.json"))
    synthetic = os.path.exists(os.path.join(a.data, "SYNTHETIC"))
    notes = _data_notes(tables, synthetic) + [
        f"Constants tuned on {a.tune_start}..{a.tune_end} (coordinate descent, {a.passes} pass(es), every "
        f"{a.stride} date(s)); this report covers the untouched holdout {a.holdout_start}..{a.holdout_end}.",
        "Edge thresholds: " + ", ".join(f"{k}={v:.0%}" for k, v in thresholds.items())]
    for k, v in bt.items():
        v.to_csv(os.path.join(a.out, f"bt_{k}.csv"), index=False)
    summary, _ = run_validation(bt, tables, best, a.out, f"Holdout validation {a.holdout_start} to {a.holdout_end}",
                                notes, thresholds, date_from=a.holdout_start)
    print(summary[["market", "line", "n", "logloss", "logloss_base", "ece", "status"]].to_string(index=False))
    print(f"-> {a.out}/tuned_config.json, {a.out}/validation.md")


def cmd_slate(a):
    from .report import slate_markdown, write
    from .slate import price_slate
    tables = load_dir(a.data)
    cfg = _cfg(a.config)
    sched = pd.read_csv(a.schedule, parse_dates=["date"])
    lineups = pd.read_csv(a.lineups)
    odds = pd.read_csv(a.odds) if a.odds else None
    hist = None
    if a.history:
        hist = {"games": pd.read_csv(os.path.join(a.history, "bt_games.csv"), parse_dates=["date"]),
                "players": pd.read_csv(os.path.join(a.history, "bt_players.csv"), parse_dates=["date"])}
    date = sched.date.min()
    plays, cons, warnings, _ = price_slate(tables, sched, lineups, odds, cfg, hist, date)
    os.makedirs(a.out, exist_ok=True)
    plays.to_csv(os.path.join(a.out, "plays.csv"), index=False)
    write(os.path.join(a.out, "slate.md"), slate_markdown(plays, cons, warnings, date))
    print(f"{len(plays)} plays priced, {int(plays.flag.sum())} flagged -> {a.out}/slate.md")


def main(argv=None):
    p = argparse.ArgumentParser(prog="nhlmodel")
    sub = p.add_subparsers(dest="cmd", required=True)
    s = sub.add_parser("synth"); s.add_argument("--out", default="data/synthetic")
    s.add_argument("--seed", type=int, default=7); s.add_argument("--seasons", type=int, nargs="+", default=[2024, 2025])
    s.set_defaults(fn=cmd_synth)
    s = sub.add_parser("build"); s.add_argument("--raw", default="data/raw"); s.add_argument("--out", default="data/processed")
    s.add_argument("--start", required=True); s.add_argument("--end", required=True); s.set_defaults(fn=cmd_build)
    s = sub.add_parser("backtest"); s.add_argument("--data", required=True); s.add_argument("--start", required=True)
    s.add_argument("--end", required=True); s.add_argument("--config"); s.add_argument("--out", default="out/backtest")
    s.add_argument("--stride", type=int, default=1); s.set_defaults(fn=cmd_backtest)
    s = sub.add_parser("tune"); s.add_argument("--data", required=True)
    for k in ("tune-start", "tune-end", "holdout-start", "holdout-end"):
        s.add_argument(f"--{k}", required=True)
    s.add_argument("--config"); s.add_argument("--out", default="out/tune"); s.add_argument("--passes", type=int, default=1)
    s.add_argument("--stride", type=int, default=2); s.add_argument("--params", help="comma list subset of the grid")
    s.set_defaults(fn=cmd_tune)
    s = sub.add_parser("slate"); s.add_argument("--data", required=True); s.add_argument("--schedule", required=True)
    s.add_argument("--lineups", required=True); s.add_argument("--odds"); s.add_argument("--config")
    s.add_argument("--history", help="dir with bt_games.csv / bt_players.csv from a backtest")
    s.add_argument("--out", default="out/slate"); s.set_defaults(fn=cmd_slate)
    a = p.parse_args(argv)
    a.fn(a)


if __name__ == "__main__":
    main()
