[theme]
base = "light"
primaryColor = "#1f3448"
backgroundColor = "#bfe0f2"
secondaryBackgroundColor = "#fffaf0"
textColor = "#1f3448"

[server]
headless = true

[client]
toolbarMode = "minimal"
showSidebarNavigation = false
